version: '3.8'

services:
    redis:
        image: redis:latest
        container_name: graphql-redis 
        ports:
            - "6380:6379"
        volumes:
            - redis_data:/data
        command: redis-server

    redisinsight:
        image: redislabs/redisinsight:latest
        container_name: graphql-redisinsight  
        ports:
            - "8002:8001"

    rabbitmq:
        image: 331leo/rabbitmq3-management-mqtt
        container_name: graphql-rabbitmq  
        hostname: rabbitmq
        environment:
            HOSTNAME: rabbitmq
            RABBITMQ_NODENAME: rabbitmq
            RABBITMQ_DEFAULT_USER: 'guest'
            RABBITMQ_DEFAULT_PASS: 'guest'
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        ports:
            - '5674:5672'
            - '15674:15672'

    mongodb:
        image: mongo:latest
        container_name: graphql-mongodb  
        environment:
            MONGODB_DATABASE: development
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
            - '27018:27017'
        volumes:
            - mongodb_data:/data/db

    mongo-express:
        image: mongo-express:latest
        container_name: graphql-mongo-express 
        ports:
            - '8082:8081'
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_URL: "mongodb://admin:admin@mongodb:27017/development"
        depends_on:
            - mongodb

    timescaledb:
        image: timescale/timescaledb:latest-pg14
        container_name: graphql-timescaledb  
        environment:
            POSTGRES_DB: development
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - '5434:5432'
        volumes:
            - timescaledb_data:/var/lib/postgresql/data

volumes:
    rabbitmq_data:
    mongodb_data:
    timescaledb_data:
    redis_data:
